### ISSUE TITLE
US06 - Submit Language Certificate

### ISSUE THREAD

**Issue by aleronupe** [translate-me/profile#3]
## Description
This issue is intended to develop, at the Backend level (using Django framework), the necessary views and models to allow an user to send its Language Certificate.

## Acceptance Criteria

- [ ] The Certificate File should be saved on database
- [ ] There should be a function responsible for getting the Certificate File and saving it, performing necessary validation
- [ ] There should be a function allowing a determined user to visualize the Certificate File
- [ ] Classes created on View files should use the generics type

**Comment by mbslet** [comment]
The file format must be an image, right?
